project_name: godescribe

builds:
  - id: godescribe
    main: ./cmd/godescribe
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "-s -w"

archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  files:
    - README.md
    - LICENSE

release:
  github:
    owner: fredmenez
    name: godescribe
    # You can set the GITHUB_TOKEN environment variable
    # or add other release configurations here as needed.
