version: 2

project_name: godescribe

builds:
  - id: main
    main: .
    binary: godescribe
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "-s -w"

archives:
  - id: archive-tar
    builds:
      - main
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: fredmenez
    name: godescribe
    # You can set the GITHUB_TOKEN environment variable
    # or add other release configurations here as needed.
