package main

import (
	"bytes"
	"text/template"
)

const (
	symbolsTpl = "package main\n" +
		"\n" +
		"// File automatically generated by github.com/fredmenez/godescribe\n" +
		"// Your changes will be lost if thsi file is regenerated\n" +
		"\n" +
		"var (\n" +
		"    SymbolsJson = `{{.}}`\n" +
		")\n"
)

func GenGenerator(symbolsInfo string) (string, error) {
	t, e := template.New("symbols").Parse(symbolsTpl)
	if e != nil {
		return "", e
	}

 	var buf bytes.Buffer
	t.Execute(&buf, symbolsInfo)
    s := buf.String()
    
    return s, nil
}
